edited github action to push the code to server and deploy

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -23,6 +23,11 @@ jobs:
           node-version: "20"
           cache: "npm"
 
+      - name: Use dev environment for build
+        run: |
+          test -f .env.dev || (echo "Missing .env.dev in the repository." && exit 1)
+          cp .env.dev .env
+
       - name: Install dependencies
         run: npm ci
 
